### ISSUE TITLE
SyntaxError in v1.4.1

### ISSUE THREAD

**Issue by PackeTsar** [meraki/dashboard-api-python#131]
Getting the below Syntax Error on v1.4.1 when installing from PIP with `pip3 install meraki`

```
(X) ~/Desktop/X/project$ 
(X) ~/Desktop/X/project$ 
(X) ~/Desktop/X/project$ 
(X) ~/Desktop/X/project$ python3 project/manage.py 
Traceback (most recent call last):
  File "project/manage.py", line 22, in <module>
    main()
  File "project/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/SOMEFOLDER/X/project/project/switches/models.py", line 9, in <module>
    from .functions import async_deploy_switch, get_switch_stats
  File "/SOMEFOLDER/X/project/project/switches/functions.py", line 7, in <module>
    import meraki
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/meraki/__init__.py", line 5, in <module>
    from .rest_session import *
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/meraki/rest_session.py", line 13, in <module>
    from .__init__ import __version__
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/meraki/__init__.py", line 9, in <module>
    from .api.appliance import Appliance
  File "/SOMEFOLDER/X/lib/python3.7/site-packages/meraki/api/appliance.py", line 1483
            """
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xae in position 284: invalid start byte
(X) ~/Desktop/X/project$ 
(X) ~/Desktop/X/project$ 
(X) ~/Desktop/X/project$ 
(X) ~/Desktop/X/project$ 
```

**Comment by TKIPisalegacycipher** [comment]
Thanks for reporting this. Looks like the documentation strings in our
OpenAPI spec contain non-UTF-8 special characters in what may be a
Mac-specific encoding.

We can fix this in the OpenAPI spec, as it's not specific to the SDK.
Easiest thing to do in the meantime is rollback to v1.4.0 (pip install
meraki==1.4.0)

Kindly,

**Comment by PackeTsar** [comment]
Yep no problem. Figured y'all would want to know about this quickly.

**Comment by TKIPisalegacycipher** [comment]
Code fixed with latest commit; will generate new PyPI packages shortly.
