### ISSUE TITLE
Syntax error in v1.4.2, looks similar to issue #131

### ISSUE THREAD

**Issue by jc516229** [meraki/dashboard-api-python#133]
With 1.4.2 on a Mac, I'm getting...

```
Traceback (most recent call last):
  File "mrssids.py", line 7, in <module>
    import meraki.aio
  File "/Users/sungod/.pyenv/versions/3.8.1/lib/python3.8/site-packages/meraki/aio/__init__.py", line 9, in <module>
    from .api.appliance import AsyncAppliance
  File "/Users/sungod/.pyenv/versions/3.8.1/lib/python3.8/site-packages/meraki/aio/api/appliance.py", line 1477
    """
    ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xae in position 284: invalid start byte

```
Reverted to 1.4.0 for now

**Comment by jc516229** [comment]
It's line 1482 in aio/api/appliance.py the registered trademark symbol

looks like the fixes for #131 were not also made to the aio files

**Comment by TKIPisalegacycipher** [comment]
Thank you for reporting this! You are right. It looks like it's the same three characters across the same three files, except in the aio/api folder.

```
meraki$ grep -axvr --include \*.py '.*' .
./aio/api/appliance.py:        - allowedRules (array): Sets a list of specific SNORT signatures to allow
./aio/api/switch.py:        - interfaceIp (string): TheIP address of the interface where the RP needs to be created.
./aio/api/wireless.py:        - mandatoryDhcpEnabled (boolean): If true, Mandatory DHCP will enforce that clients connecting to this SSID must use the IP address assigned by the DHCP server. Clients who use a static IP address wont be able to associate.
```

As mentioned before, this needs to be fixed upstream (OpenAPI spec) and I expect that to happen in calendar Q1.

**Comment by TKIPisalegacycipher** [comment]
SDK package has been updated on PyPI. Thanks again for reporting. Happy holidays! https://pypi.org/project/meraki/#history
