### ISSUE TITLE
appliance.py getting syntax err in position 284

### ISSUE THREAD

**Issue by Rupert-Wever** [meraki/dashboard-api-python#143]
Starting a brand-new pycharm project with bare basics:

_____
import meraki

if __name__ == '__main__':
    print('Hello')
_____

Getting the following...

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rwever/PycharmProjects/MerakiUtils/venv/lib/python3.8/site-packages/meraki/__init__.py", line 5, in <module>
    from .rest_session import *
  File "/Users/rwever/PycharmProjects/MerakiUtils/venv/lib/python3.8/site-packages/meraki/rest_session.py", line 13, in <module>
    from .__init__ import __version__
  File "/Users/rwever/PycharmProjects/MerakiUtils/venv/lib/python3.8/site-packages/meraki/__init__.py", line 9, in <module>
    from .api.appliance import Appliance
  File "/Users/rwever/PycharmProjects/MerakiUtils/venv/lib/python3.8/site-packages/meraki/api/appliance.py", line 1477
    """
    ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xae in position 284: invalid start byte
python-BaseException

**Comment by Rupert-Wever** [comment]
Error occurring with 1.6.0
Workaround = pip3 install meraki==1.4.3

**Comment by TKIPisalegacycipher** [comment]
Fixed in https://github.com/meraki/dashboard-api-python/commit/c9928d646b51a1ab25d680732d038af3240c058a
