### ISSUE TITLE
Update Python SDK to v1.6.0 (Unicode error)

### ISSUE THREAD

**Issue by ddexterpark** [meraki/dashboard-api-python#144]
Hello,

It looks like the update to [SDK v1.6.0](https://github.com/meraki/dashboard-api-python/commit/5f5e552fefe03ceb93f37cbca92a3247ad05f4a4)  replaced a trademark character which is causing unicode issues:

Traceback (most recent call last):
  File "audit.py", line 1, in <module>
    import meraki
  File "/$MY_PATH/venv/lib/python3.7/site-packages/meraki/__init__.py", line 5, in <module>
    from .rest_session import *
  File "/$MY_PATH/venv/lib/python3.7/site-packages/meraki/rest_session.py", line 13, in <module>
    from .__init__ import __version__
  File "/$MY_PATH/venv/lib/python3.7/site-packages/meraki/__init__.py", line 9, in <module>
    from .api.appliance import Appliance
  File "/$MY_PATH/venv/lib/python3.7/site-packages/meraki/api/appliance.py", line 1483
            """
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xae in position 284: invalid start byte
(venv) 

Please replace`SNORT®` with ` SNORT(r)` on line 1482 for: 

meraki/aio/api/appliance.py 
meraki/api/appliance.py 

Thanks in advance!

**Comment by ddexterpark** [comment]
I've opened a pull request to address this issue: https://github.com/meraki/dashboard-api-python/pull/145

Pending review. Thanks in advance!

**Comment by TKIPisalegacycipher** [comment]
Thank you. This is fixed; I also resolved this within the generate_library.py module to help avoid this in the future. https://github.com/meraki/dashboard-api-python/commit/c9928d646b51a1ab25d680732d038af3240c058a
