### ISSUE TITLE
getOrganizationWirelessSsidsStatusesByDevice KeyError

### ISSUE THREAD

**Issue by sloweclair** [meraki/dashboard-api-python#270]
**Describe how you confirmed the issue is with the library, and not with the API itself, or a server-side issue of some other kind.**
The python library is trying to read `pageEndAt` when it isn't there in a response

**Python version installed**
3.12.4

**Meraki library version installed**
1.51.0

**Have you reproduced the issue with the latest version of this library? And with the latest version of Python?**
Yes

**OS Platform**
Windows 11

**Describe the bug**
The `getOrganizationWirelessSsidsStatusesByDevice` crashes when there is more than 1 page. It is trying to read `pageEndAt` from the `response.json()` but it isn't there.

```
Traceback (most recent call last):
  File "meraki-bug-check\crash.py", line 5, in <module>
    data = dashboard.wireless.getOrganizationWirelessSsidsStatusesByDevice(<redacted>, total_pages=-1, networkIds=['<redacted>'], perPage=500)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "meraki-bug-check\.venv\Lib\site-packages\meraki\api\wireless.py", line 3018, in getOrganizationWirelessSsidsStatusesByDevice
    return self._session.get_pages(metadata, resource, params, total_pages, direction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "meraki-bug-check\.venv\Lib\site-packages\meraki\rest_session.py", line 457, in _get_pages_legacy
    end = response.json()['pageEndAt']
          ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'pageEndAt'
```

**How can we replicate the problem you're reporting?**
Run the code snippet below. It will crash as long as it is requesting more than 1 page

**Expected behavior**
Not crash

**Code snippets**
```
import meraki
dashboard = meraki.DashboardAPI()
data = dashboard.wireless.getOrganizationWirelessSsidsStatusesByDevice(<redacted>, total_pages=-1, networkIds=['<redacted>'], perPage=100)
print(data)
```

**Comment by TKIPisalegacycipher** [comment]
Hi @sloweclair are you still seeing this issue in v1.54.0 of the library?

**Comment by BraydenNeale** [comment]
This is still an issue in the latest Meraki version `1.56.0`

```
meraki\api\switch.py", line 2629, in getOrganizationSwitchPortsClientsOverviewByDevice
    return self._session.get_pages(metadata, resource, params, total_pages, direction)
meraki\rest_session.py", line 457, in _get_pages_legacy
    end = response.json()['pageEndAt']
KeyError: 'pageEndAt'
```

Recreation: Meraki Python Library Code snippet at:
https://developer.cisco.com/meraki/api-v1/get-organization-switch-ports-clients-overview-by-device/

`_get_pages_legacy` in `rest_session.py`
```
           ...
            elif isinstance(results, dict):
                try:
                    start = response.json()['pageStartAt']
                except KeyError:
                    print(response.headers)
                end = response.json()['pageEndAt']
                events = response.json()['events']
            ...
```
`response.json` has an 'items' array instead 'events' and no page properties.
```
{
    "items": [
        {
            "name": "Example Switch",
            "serial": "Q555-5555-5555",
            "mac": "01:23:45:67:ab:cd",
            "network": {
                "name": "Example Network",
                "id": "L_12345"
            },
            "model": "MS120-8",
            "ports": [
                {
                    "portId": "1",
                    "counts": {
                        "byStatus": {
                            "online": 0
                        }
                    }
                }
            ]
        }
    ],
    "meta": {
        "counts": {
            "items": {
                "total": 1,
                "remaining": 0
            }
        }
    }
}
```

**Comment by TKIPisalegacycipher** [comment]
Fixed in commit 8791aa5c1d25beb0d66472116b826534d667eb15
